use mir::types::MirReg;
use crate::alias_graph::AliasGraph;
use crate::escape::EscapeAnalysis;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MemoryClass {
    /// Function-local Arena allocation (tied to a specific region ID)
    Arena(u32),
    /// Function-local Stack allocation (for acyclic, fixed-size types < 256 bytes)
    Stack,
    /// Function-local Heap allocation (Owned exclusively by this scope, dropped at end)
    Owned,
    /// Reference Counted Heap allocation (Can escape, is shared, managed via RC)
    Shared,
    /// A parameter that does not escape. Bypasses RC operations locally.
    Borrow,
    /// Primitive value (number, boolean, null, undefined). Not managed by CIRC.
    Primitive,
}

pub struct Classification {
    pub classes: HashMap<MirReg, MemoryClass>,
}

impl Classification {
    pub fn new() -> Self {
        Self {
            classes: HashMap::new(),
        }
    }

    pub fn set_class(&mut self, reg: MirReg, class: MemoryClass) {
        self.classes.insert(reg, class);
    }

    pub fn get_class(&self, reg: MirReg) -> MemoryClass {
        // Default to Shared if unclassified for safety.
        *self.classes.get(&reg).unwrap_or(&MemoryClass::Shared)
    }
}

pub fn classify_registers(
    func: &mir::MirFunction,
    alias_graph: &AliasGraph,
    escape: &EscapeAnalysis,
    module_ea: &std::collections::HashMap<String, EscapeAnalysis>,
    signature: Option<&[MemoryClass]>,
) -> Classification {
    let mut class = Classification::new();

    // First pass: identify primitives definitively generated by instructions
    let mut primitives = std::collections::HashSet::new();
    let mut allocations = std::collections::HashSet::new();
    for block in &func.blocks {
        for instr in &block.instrs {
            use mir::types::MirInstr::*;
            match instr {
                Add(dest, _, _) | Sub(dest, _, _) | Mul(dest, _, _) | Div(dest, _, _) |
                Mod(dest, _, _) | Exp(dest, _, _) | Neg(dest, _) | Plus(dest, _) |
                Eq(dest, _, _) | Ne(dest, _, _) | StrictEq(dest, _, _) | StrictNe(dest, _, _) |
                Lt(dest, _, _) | Le(dest, _, _) | Gt(dest, _, _) | Ge(dest, _, _) |
                In(dest, _, _) | Not(dest, _) | BitAnd(dest, _, _) | BitOr(dest, _, _) |
                BitXor(dest, _, _) | Shl(dest, _, _) | Shr(dest, _, _) | UShr(dest, _, _) |
                BitNot(dest, _) => {
                    primitives.insert(*dest);
                }
                Move(dest, op) => {
                    if let mir::types::MirOperand::ConstNum(_) | mir::types::MirOperand::ConstBool(_) |
                           mir::types::MirOperand::ConstNull | mir::types::MirOperand::ConstUndefined = op {
                        primitives.insert(*dest);
                    } else if let mir::types::MirOperand::Reg(src) = op {
                        if allocations.contains(src) {
                            allocations.insert(*dest);
                        }
                        if primitives.contains(src) {
                            primitives.insert(*dest);
                        }
                    }
                }
                Alloc(dest, _) | AllocShared(dest, _) | AllocAcyclic(dest, _) | AllocSharedAcyclic(dest, _) | AllocOwned(dest, _) | AllocStack(dest, _) | AllocArena(dest, _, _) | AllocClosure(dest, _, _) | AllocSharedClosure(dest, _, _) | AllocOwnedClosure(dest, _, _) => {
                    allocations.insert(*dest);
                }
                CallDirect(dest, target, _) | CallPure(dest, target, _) => {
                    let mut returns_fresh = false;
                    let mut returns_primitive = false;
                    if let Some(sig) = crate::native_sigs::NativeSignature::get(target) {
                        returns_fresh = sig.returns_fresh_allocation;
                        returns_primitive = sig.returns_primitive;
                    }
                    if let Some(target_ea) = module_ea.get(target) {
                        if target_ea.returns_fresh_allocation {
                            returns_fresh = true;
                        }
                    }

                    if returns_primitive {
                        primitives.insert(*dest);
                    } else if returns_fresh {
                        allocations.insert(*dest);
                    }
                }
                CallBuiltin(dest, builtin, _) => {
                    use mir::BuiltinFn;
                    
                    let returns_primitive = matches!(builtin,
                        BuiltinFn::ConsoleLog |
                        BuiltinFn::ArrayLength |
                        BuiltinFn::ArrayIndexOf |
                        BuiltinFn::ArrayIncludes
                    );
                    
                    let returns_fresh = matches!(builtin,
                        BuiltinFn::ArrayMap |
                        BuiltinFn::ArrayFilter |
                        BuiltinFn::ArraySlice |
                        BuiltinFn::ArrayConcat
                    );
                    
                    if returns_primitive {
                        primitives.insert(*dest);
                    } else if returns_fresh {
                        allocations.insert(*dest);
                    }
                }
                _ => {}
            }
        }
    }

    let mut is_shared = std::collections::HashSet::new();
    let mut move_deps: HashMap<MirReg, Vec<MirReg>> = HashMap::new();

    for block in &func.blocks {
        for instr in &block.instrs {
            if let mir::types::MirInstr::Move(dest, mir::types::MirOperand::Reg(src)) = instr {
                move_deps.entry(*dest).or_default().push(*src);
            } else if let mir::types::MirInstr::StoreField(dest, _, mir::types::MirOperand::Reg(src)) = instr {
                move_deps.entry(*dest).or_default().push(*src);
            } else if let mir::types::MirInstr::StoreSharedField(dest, _, mir::types::MirOperand::Reg(src), _) = instr {
                move_deps.entry(*dest).or_default().push(*src);
            } else if let mir::types::MirInstr::StoreProp(dest, _, mir::types::MirOperand::Reg(src), _) = instr {
                move_deps.entry(*dest).or_default().push(*src);
            } else if let mir::types::MirInstr::AllocClosure(dest, _, captures) = instr {
                for cap in captures {
                    if let mir::types::MirOperand::Reg(src) = cap {
                        move_deps.entry(*dest).or_default().push(*src);
                    }
                }
            }
        }
    }

    let mut is_borrow = std::collections::HashSet::new();
    for (idx, (reg, _)) in func.params.iter().enumerate() {
        if let Some(sig) = signature {
            if idx > 0 && (idx - 1) < sig.len() {
                match sig[idx - 1] {
                    MemoryClass::Borrow | MemoryClass::Arena(_) => { is_borrow.insert(*reg); }
                    MemoryClass::Shared => { is_shared.insert(*reg); }
                    MemoryClass::Owned => { allocations.insert(*reg); }
                    MemoryClass::Primitive => { primitives.insert(*reg); }
                    _ => {}
                }
            }
        }
        
        if let Some(&escapes) = escape.param_escapes.get(idx) {
            if !escapes {
                is_borrow.insert(*reg);
            }
        }
    }

    let mut forward_moves: HashMap<MirReg, Vec<MirReg>> = HashMap::new();
    for block in &func.blocks {
        for instr in &block.instrs {
            if let mir::types::MirInstr::Move(dest, mir::types::MirOperand::Reg(src)) = instr {
                forward_moves.entry(*src).or_default().push(*dest);
            }
        }
    }

    let mut borrow_worklist: Vec<MirReg> = is_borrow.iter().copied().collect();
    while let Some(reg) = borrow_worklist.pop() {
        if let Some(dests) = forward_moves.get(&reg) {
            for &dest in dests {
                if is_borrow.insert(dest) {
                    borrow_worklist.push(dest);
                }
            }
        }
    }

    let mut alloc_worklist: Vec<MirReg> = allocations.iter().copied().collect();
    while let Some(reg) = alloc_worklist.pop() {
        if let Some(dests) = forward_moves.get(&reg) {
            for &dest in dests {
                if allocations.insert(dest) {
                    alloc_worklist.push(dest);
                }
            }
        }
    }

    for reg in 0..func.next_reg {
        if !primitives.contains(&reg) && !is_borrow.contains(&reg) {
            if escape.prevents_owned(reg) || alias_graph.is_aliased(reg) {
                is_shared.insert(reg);
            } else if !allocations.contains(&reg) {
                is_shared.insert(reg);
            }
        }
    }

    let mut worklist: Vec<MirReg> = is_shared.iter().copied().collect();
    while let Some(reg) = worklist.pop() {
        if let Some(sources) = move_deps.get(&reg) {
            for &src in sources {
                if is_shared.insert(src) {
                    worklist.push(src);
                }
            }
        }
    }

    for reg in 0..func.next_reg {
        if primitives.contains(&reg) {
            class.set_class(reg, MemoryClass::Primitive);
        } else if is_borrow.contains(&reg) {
            class.set_class(reg, MemoryClass::Borrow);
        } else if is_shared.contains(&reg) {
            class.set_class(reg, MemoryClass::Shared);
        } else if allocations.contains(&reg) {
            class.set_class(reg, MemoryClass::Owned);
        } else {
            class.set_class(reg, MemoryClass::Shared);
        }
    }

    class
}
