use mir::types::MirReg;
use crate::alias_graph::AliasGraph;
use crate::escape::EscapeAnalysis;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryClass {
    /// Allocated on the execution stack (primitives or escaping scalar replacements).
    Stack,
    /// Allocated in a specific bump-pointer arena region (Phase 4).
    Arena(u32),
    /// Uniquely owned, heap-allocated without reference count. Dropped at last use.
    Owned,
    /// Shared ownership, CIRC-managed (rc inc/dec).
    Shared,
    /// Primitive value (number, boolean, null, undefined). Not managed by CIRC.
    Primitive,
}

pub struct Classification {
    pub classes: HashMap<MirReg, MemoryClass>,
}

impl Classification {
    pub fn new() -> Self {
        Self {
            classes: HashMap::new(),
        }
    }

    pub fn set_class(&mut self, reg: MirReg, class: MemoryClass) {
        self.classes.insert(reg, class);
    }

    pub fn get_class(&self, reg: MirReg) -> MemoryClass {
        // Default to Shared if unclassified for safety.
        *self.classes.get(&reg).unwrap_or(&MemoryClass::Shared)
    }
}

pub fn classify_registers(
    func: &mir::MirFunction,
    alias_graph: &AliasGraph,
    escape: &EscapeAnalysis,
) -> Classification {
    let mut class = Classification::new();

    // First pass: identify primitives definitively generated by instructions
    let mut primitives = std::collections::HashSet::new();
    for block in &func.blocks {
        for instr in &block.instrs {
            use mir::types::MirInstr::*;
            match instr {
                Add(dest, _, _) | Sub(dest, _, _) | Mul(dest, _, _) | Div(dest, _, _) |
                Mod(dest, _, _) | Exp(dest, _, _) | Neg(dest, _) | Plus(dest, _) |
                Eq(dest, _, _) | Ne(dest, _, _) | StrictEq(dest, _, _) | StrictNe(dest, _, _) |
                Lt(dest, _, _) | Le(dest, _, _) | Gt(dest, _, _) | Ge(dest, _, _) |
                In(dest, _, _) | Not(dest, _) | BitAnd(dest, _, _) | BitOr(dest, _, _) |
                BitXor(dest, _, _) | Shl(dest, _, _) | Shr(dest, _, _) | UShr(dest, _, _) |
                BitNot(dest, _) => {
                    primitives.insert(*dest);
                }
                Move(dest, op) => {
                    if let mir::types::MirOperand::ConstNum(_) | mir::types::MirOperand::ConstBool(_) |
                           mir::types::MirOperand::ConstNull | mir::types::MirOperand::ConstUndefined = op {
                        primitives.insert(*dest);
                    }
                }
                _ => {}
            }
        }
    }

    for reg in 0..func.next_reg {
        if primitives.contains(&reg) {
            class.set_class(reg, MemoryClass::Primitive);
        } else if escape.prevents_owned(reg) {
            // Escapes into another object or unknown call -> must be Shared
            class.set_class(reg, MemoryClass::Shared);
        } else if alias_graph.is_aliased(reg) {
            // Multiple live references -> must be Shared
            class.set_class(reg, MemoryClass::Shared);
        } else {
            // Non-escaping (or return-only escape), non-aliased -> Owned
            class.set_class(reg, MemoryClass::Owned);
        }
    }

    class
}
